function [S1vector,S2vector] = EEheightSvectors(dp1,dp2,nj1,nj2,nk1,nk2,vj1,vj2,vk1,vk2)
%EEHEIGHTSVECTORS
%    [S1VECTOR,S2VECTOR] = EEHEIGHTSVECTORS(DP1,DP2,NJ1,NJ2,NK1,NK2,VJ1,VJ2,VK1,VK2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-Apr-2021 16:41:09

t2 = nj1.*nk2;
t3 = nj2.*nk1;
t4 = -t3;
t5 = t2+t4;
t6 = 1.0./t5;
S1vector = [t6.*(dp1.*nk1+dp2.*nk2),-t6.*(dp1.*nk2-dp2.*nk1),t6.*(nk1.*vj1+nk2.*vj2-nk1.*vk1-nk2.*vk2)];
if nargout > 1
    S2vector = [t6.*(dp1.*nj1+dp2.*nj2),-t6.*(dp1.*nj2-dp2.*nj1),t6.*(nj1.*vj1+nj2.*vj2-nj1.*vk1-nj2.*vk2)];
end
