function Dvector = EEheightDvector(dp1,dp2,nj1,nj2,nk1,nk2,vj1,vj2,vk1,vk2)
%EEHEIGHTDVECTOR
%    DVECTOR = EEHEIGHTDVECTOR(DP1,DP2,NJ1,NJ2,NK1,NK2,VJ1,VJ2,VK1,VK2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    29-Mar-2021 17:45:23

t2 = nj1.^2;
t3 = nj2.^2;
t4 = nk1.^2;
t5 = nk2.^2;
t6 = dp1.*nj1.*nk2;
t7 = dp2.*nj1.*nk2;
t8 = nj1.*nj2.*nk1.*nk2.*2.0;
t9 = -t6;
t10 = -t7;
t11 = -t8;
t12 = t2.*t5;
t13 = t3.*t4;
t14 = t11+t12+t13;
t15 = 1.0./t14;
Dvector = [(t15.*(t7-dp2.*t3-dp1.*nj1.*nj2+dp1.*nj1.*nk1))./2.0,t15.*(t6-dp1.*t3+dp2.*nj1.*nj2-dp2.*nj1.*nk1).*(-1.0./2.0)-(t15.*(t6-dp1.*t4+dp2.*nj2.*nk2-dp2.*nk1.*nk2))./2.0,vj2.*(-1.0./2.0)-vk2./2.0-(t15.*(t3.*vj2-t3.*vk2+nj1.*nj2.*vj1-nj1.*nk1.*vj1-nj1.*nj2.*vk1-nj1.*nk2.*vj2+nj1.*nk1.*vk1+nj1.*nk2.*vk2))./2.0,t15.*(t7-dp2.*t4-dp1.*nj2.*nk2+dp1.*nk1.*nk2).*(-1.0./2.0),vj1.*(-1.0./2.0)-vk1./2.0+(t15.*(t4.*vj1-t4.*vk1-nj1.*nk2.*vj1-nj2.*nk2.*vj2+nj1.*nk2.*vk1+nk1.*nk2.*vj2+nj2.*nk2.*vk2-nk1.*nk2.*vk2))./2.0,dp2./2.0];
